// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvsGmLVgp0gn_LixYTm9_lug2c6lS5F20',
    appId: '1:1002778254209:web:e43724505f755f73b6a680',
    messagingSenderId: '1002778254209',
    projectId: 'gourmet-go-a9616',
    authDomain: 'gourmet-go-a9616.firebaseapp.com',
    storageBucket: 'gourmet-go-a9616.appspot.com',
    measurementId: 'G-731SMFEPPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhuZP7R_BIQ75uG8UVNrrYfnsY-0Uyoo',
    appId: '1:1002778254209:android:f12fc035d4fc2089b6a680',
    messagingSenderId: '1002778254209',
    projectId: 'gourmet-go-a9616',
    storageBucket: 'gourmet-go-a9616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGYQ1IYbLC7-ZMAlHzqXPlmwaQl-QNYOw',
    appId: '1:1002778254209:ios:1fbd39a84e3a86b5b6a680',
    messagingSenderId: '1002778254209',
    projectId: 'gourmet-go-a9616',
    storageBucket: 'gourmet-go-a9616.appspot.com',
    iosBundleId: 'com.example.gourmetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGYQ1IYbLC7-ZMAlHzqXPlmwaQl-QNYOw',
    appId: '1:1002778254209:ios:26e76d51fe561d00b6a680',
    messagingSenderId: '1002778254209',
    projectId: 'gourmet-go-a9616',
    storageBucket: 'gourmet-go-a9616.appspot.com',
    iosBundleId: 'com.example.gourmetApp.RunnerTests',
  );
}
